### ISSUE TITLE
Adapter startet nicht mehr

### ISSUE THREAD

**Issue by reihd** [ice987987/ioBroker.husqvarna-automower#118]
### The problem

der Adapter startet nicht mehr. Hier das Log

 starting. Version 0.4.0-beta.3 (non-npm: ice987987/ioBroker.husqvarna-automower#6339d7b584f59c1874ad3c647536996077de3a0e) in /opt/iobroker/node_modules/iobroker.husqvarna-automower, node: v18.16.0, js-controller: 4.0.24

### Version of "husqvarna-automower"-adapter

v0.4.0-beta.3

### Husqvarna Automower Type

405x

### Version of Node.js

v18.16.0

### Version of ioBroker js-controller

9.5.1

### Version of "admin"-adapter

6.3.5

### Operating system incl. version running ioBroker

Linux Debian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode and check that there are no personal information)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by ice987987** [comment]
dublicate https://github.com/ice987987/ioBroker.husqvarna-automower/issues/117
