### ISSUE TITLE
Schedules werden nicht angezeigt

### ISSUE THREAD

**Issue by reutli** [ice987987/ioBroker.husqvarna-automower#12]
Der Adapter zeigt in keinem der drei Kalender die 'schedules' an, die eingerichtet sind.
Nach meinem Verständnis müsste er doch bereits im Mower angelegte schedules auslesen und anzeigen?

<img width="1547" alt="Bildschirmfoto 2022-04-18 um 09 11 51" src="https://user-images.githubusercontent.com/62477965/163771084-c00a59da-694a-4291-b031-ff4658c3271a.png">

**Comment by reutli** [comment]
Muss korrigieren: die schedules werden unter 'calendar' angezeigt. - SORRY!

Wie werden die schedules aber angepasst? Wird dies im 'calender' vollzogen oder unter 'ACTIONS/schedules'?
Laut Doku sind die 'calendar' read-only.

**Comment by ice987987** [comment]
Die Schedules können entweder in der husqvarna-app oder auf dem Mäher angepasst werden. In diesem Fall sollten diese Werte unter den DP's `.calendar.[0-3].[xxx]` angezeigt/aktualisiert werden.
Im ioBroker können die Schedules unter `.ACTIONS.schedule.[0-3].[xxx]` voreingestellt werden. Übermittelt an den Mäher werden diese anschliessend mit dem `true` im DP `.ACTIONS.schedule.SET`. Sind diese erfolgreich übermittelt, werden die DP's unter `.calendar.[0-3].[xxx]` entsprechend aktualisiert.

siehe ggf. auch https://github.com/ice987987/ioBroker.husqvarna-automower#control

**Comment by ice987987** [comment]
Hat sich diese Anfrage geklärt? Wenn ja, bitte ich um deren Schliessung.

**Comment by reutli** [comment]
done
