### ISSUE TITLE
.ACTIONS.start.START without overriding schedule

### ISSUE THREAD

**Issue by KamikazePL84** [ice987987/ioBroker.husqvarna-automower#14]
Can you add .ACTIONS.start.START without overriding sched-ule? Only jus start without duration time.

**Comment by ice987987** [comment]
Do you possibly mean the following DP?

`.ACTIONS.RESUMESCHEDULE`: resume mower according to schedule

**Comment by KamikazePL84** [comment]
I would like to run the robot without specifying the working time. Now it is not possible, I have to give the working time to start working. I tried to enter "0" but it doesn't work. The robot is controlled by building automation, I am only interested in starting without a time limit and returning to the base waiting for the next command.

**Comment by ice987987** [comment]
According to my understanding from husqvarna's-API this is not possible. Please find [here](https://developer.husqvarnagroup.cloud/apis/Automower+Connect+API#/readme) all the available commands.

perhaps it is possible to enter one schedule, all days, from 00:00 to 23:59 and let the mower run accordingly.

**Comment by KamikazePL84** [comment]
> perhaps it is possible to enter one schedule, all days, from 00:00 to 23:59 and let the mower run accordingly.

Good idea!
