### ISSUE TITLE
Initialisierungswerte

### ISSUE THREAD

**Issue by ghifunk** [ice987987/ioBroker.husqvarna-automower#162]
### Feature or idea description

Hallo,
ist es möglich einen Initialisierungswert für die Ausgabe des gesamt gefahrenen Weges vorzusehen, damit man die Werte an die der Original Husqvarna App angleichen kann. Der Mower läuft bereits länger, als der Adapter im IoBroker . Man könnte es zwar auch extern anpassen, aber ich denke in der User Configuration des Scripts ist ein Initialisierungswert besser aufgehoben!
Danke im Voraus.!

### Version of "husqvarna-automower"-adapter

v 0.4.0 beta3 und script

**Comment by ice987987** [comment]
Die gefahrene Gesamtdistanz wird seitens der API im Datenpunkt `husqvarna-automower.x.y.statistics.totalDrivenDistance` zur Verfügung gestellt. ist dieser Wert `null` unterstützt das Modell diesen Wert nicht und auch in der App sollte dieser Wert nicht verfügbar sein.
