### ISSUE TITLE
Entfernung zur Basis berechnen

### ISSUE THREAD

**Issue by ghifunk** [ice987987/ioBroker.husqvarna-automower#163]
### The problem

Hallo,
Das Problem besteht in der nicht korrekten Berechnung der Entfernung des Mowers zur Ladestation. 
Dieses findet im Script zu dem Adapter statt. Im Adapter selbst werden der Längen- und Breitengrad korrekt eingetragen.
Allerdings berechnet das Skript daraus eine Entfernung von etwa 5737207,06 m. Der Mäher ist bereits einige Tage mit diesem Problem unterwegs. Ich habe versucht, die Differenz aus dem im Script berechnetem Wert mit dem aktuell ausgegebenem Wert zu bilden, was jedoch auch keine akzeptablen Ergebnisse bringt. Einzig in der Ladestation passt der Wert wieder auf 0 m.
Das Script ist das was sich momentan auf  (https://github.com/ice987987/ioBroker.husqvarna-automower) befindet und der Adapter ist Version 0.4.0-beta.3
Danke für die Hilfe!

### Version of "husqvarna-automower"-adapter

v 0.4.0-beta.3

### Husqvarna Automower Type

x415

### Version of Node.js

v18.19.0

### Version of ioBroker js-controller

5.0.19

### Version of "admin"-adapter

6.13.16

### Operating system incl. version running ioBroker

Linux (Docker)

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode and check that there are no personal information)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by ArnoD15** [comment]
Bitte das Script einmal stoppen und neu starten, wenn der Mower in der Ladestation ist, damit die Position der Ladestation neu eingetragen wird.
Wenn dann immer noch die Entfernung zur Ladestation nicht stimmt, bitte die Werte Latitude und Longitude mal bei Google Maps über diesen Link prüfen: https://www.google.com/maps/place/latitude,longiude/@?hl=de
Bitte den Text latitude,longiude mit den entsprechenden Werten austauschen.

**Comment by ice987987** [comment]
Der Wert wird fortlaufend an die gesendeten Werte (GPS-Koordinaten) angeglichen, wenn sich der Mäher sich in der Ladestation befindet. Nach ein paar Stunden sollte der Wert "etwas genauer" sein.
