### ISSUE TITLE
Warnmeldung

### ISSUE THREAD

**Issue by kanumouse** [ice987987/ioBroker.husqvarna-automower#172]
### The problem

Ich erhalte ständig diese Warnmeldung:
Read-only state "husqvarna-automower.0.info.connection" has been written without ack-flag with value "true"

### Version of "husqvarna-automower"-adapter

v 0.5.0-beta8

### Husqvarna Automower Type

315x

### Version of Node.js

v 18.19.1

### Version of ioBroker js-controller

v 5.0.19

### Version of "admin"-adapter

v 6.17.14

### Operating system incl. version running ioBroker

Raspbian GNU/Linux 11 (bullseye)

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode and check that there are no personal information)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by ice987987** [comment]
fixed, see https://github.com/sbormann/ioBroker.iqontrol/issues/312#issuecomment-2194025807
