### ISSUE TITLE
Please consider adding adapter to repositories

### ISSUE THREAD

**Issue by mcm1957** [ice987987/ioBroker.husqvarna-automower#173]
Please request addition to iobroker repositories once the adapter is working for users.
see https://github.com/ioBroker/ioBroker.repositories?tab=readme-ov-file#requirements-for-adapter-to-get-added-to-the-latest-repository

**Comment by ice987987** [comment]
see https://github.com/ice987987/ioBroker.husqvarna-automower/issues/46

**Comment by mcm1957** [comment]
I did not receive a request to add the adapter to the repositories yet.

Please follow: https://github.com/ice987987/ioBroker.husqvarna-automower/issues/46#issuecomment-2057677288
