### ISSUE TITLE
Object to see the current working area

### ISSUE THREAD

**Issue by Bambo84** [ice987987/ioBroker.husqvarna-automower#177]
### Feature or idea description

I have two feature request's.

1. 
I think it will be great, when ich can found a object, where I see in which working area my automower is working now.
And additional 
2. 
It will be great, when I find a object which shows if the automower with EPOS is searching for a GPS signal. 

### Version of "husqvarna-automower"-adapter

0.5.0-beta.8

**Comment by ice987987** [comment]
please test ioBroker.husqvarna-automower v0.6.0-beta.x

for 1) `.mower.workAreaId`
for 2) please tell me which value is missing: https://developer.husqvarnagroup.cloud/apis/automower-connect-api?tab=openapi

**Comment by ice987987** [comment]
closed due to no feedback
