### ISSUE TITLE
mower.errorCodeTimestamp is two hours in front

### ISSUE THREAD

**Issue by reutli** [ice987987/ioBroker.husqvarna-automower#178]
### The problem

If an error occurs, the timestamp is two hours ahead. See also the attached screenshots.
![Bildschirmfoto 2024-07-16 um 10 39 02](https://github.com/user-attachments/assets/f94d8087-8a28-4147-b2c7-7f2f140874ad)
![Bildschirmfoto 2024-07-16 um 10 39 14](https://github.com/user-attachments/assets/6d6f7725-a3be-4149-8bce-6202cf499a78)

### Version of "husqvarna-automower"-adapter

0.4.0

### Husqvarna Automower Type

430X

### Version of Node.js

18.20.4

### Version of ioBroker js-controller

5.0.19

### Version of "admin"-adapter

6.17.14

### Operating system incl. version running ioBroker

Linux Debian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode and check that there are no personal information)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by ice987987** [comment]
I can not reproduce this issue. Is the system time correct?

**Comment by ice987987** [comment]
closed due to no feedback

**Comment by reutli** [comment]
Opened issue in July…, answer (as a question) was end of August - sorry but also was unable to recap the issue.
Will open a new one when it comes up again.

Please try to react on issues a bit earlier, then it would be much easier to answer questions regarding the issue ;o)

Thx
