### ISSUE TITLE
Verbindung zu Gerät oder Dienst verloren

### ISSUE THREAD

**Issue by KoMa1978** [ice987987/ioBroker.husqvarna-automower#182]
### The problem

Hallo,

Der Husqvarna Adapter verliert bei mir immer wieder die Verbindung zum Gerät oder Dienst:
![image](https://github.com/user-attachments/assets/ddf60e08-dd10-43fe-bd9f-7ea91f31e612)

Gibt es hierfür eine einfache Lösung? Wie kann man es troubleshooten?
Im normalen Log ist leider nichts zu sehen ...
Ein Restart der Instanz behebt das Problem erst einmal, bis es irgendwann wieder auftritt.

Besten Dank,
 KoMa1978

### Version of "husqvarna-automower"-adapter

v0.5.0-beta.8

### Husqvarna Automower Type

415

### Version of Node.js

 v18.20.4

### Version of ioBroker js-controller

 5.0.19

### Version of "admin"-adapter

v6.17.14

### Operating system incl. version running ioBroker

Debian 12.6

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode and check that there are no personal information)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by KoMa1978** [comment]
Hallo zusammen,

ich habe mal das Logging auf Debug gestellt und dabei folgendes gesehen:
```
husqvarna-automower.0	2024-08-13 10:47:19.356	debug	[wss.close - error]: Error: Unknown WebSocket error. (ERR_#011)
husqvarna-automower.0	2024-08-13 10:47:19.356	debug	[wss.on - close]: this.wss.readyState: 3; data: 1012; reason: Service restarting
husqvarna-automower.0	2024-08-13 10:46:48.994	debug	[wss.on - message]: {"id":"xxxxxxxxxxx","type":"status-event","attributes":{"battery":{"batteryPercent":35},"mower":{"mode":"MAIN_AREA","activity":"CHARGING","state":"IN_OPERATION","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":1723550416000,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723538808895}}}
```

Ich bin kein Programmierer, aber könnte man den WSS-Error nicht abfangen und die Connection neu aufbauen?
Das wird doch in der main.js im Try/Catch Block in Zeile 1833 auch schon für andere Fehlercodes gemacht, oder?

Besten Dank

**Comment by KoMa1978** [comment]
Ich habe jetzt mal in den Block folgendes eingefügt, mal schauen ob es hilft:

```
               } else if (data === 1012) {
                    // sometimes
                    await this.getAccessToken();
                    await this.autoRestart();

```

Ich werde berichten ...

**Comment by KoMa1978** [comment]
Heute Nacht ist das Problem wieder aufgetreten, hat sich aber durch die Änderung von selber behoben:

```
2024-08-14 02:20:29.404 - debug: husqvarna-automower.0 (3164) [wss.on - close]: this.wss.readyState: 3; data: 1012; reason: Service restarting
2024-08-14 02:20:29.627 - debug: husqvarna-automower.0 (3164) [getAccessToken]: HTTP status response: 200 OK; config: {xxxxxxxxxxxxxx}
2024-08-14 02:20:29.628 - debug: husqvarna-automower.0 (3164) "Husqvarna Authentication API Access token" received.
2024-08-14 02:20:29.628 - debug: husqvarna-automower.0 (3164) [autoRestart]: WebSocket connection terminated by Husqvarna-Server. Reconnect again in 5 seconds...
2024-08-14 02:20:34.923 - debug: husqvarna-automower.0 (3164) [wss.on - open]: Connection to "Husqvarna WebSocket" re-established. Ready to get data...
2024-08-14 02:20:34.924 - debug: husqvarna-automower.0 (3164) [sendPingToServer]: WebSocket sends ping to server...
2024-08-14 02:20:34.960 - debug: husqvarna-automower.0 (3164) [wss.on - pong]: WebSocket receives pong from server.
2024-08-14 02:20:34.979 - debug: husqvarna-automower.0 (3164) [wss.on - message]: {"ready":true,"connectionId":"xxxxxxxxxxxxxx"}
```

Mein Code im "try" Block ab Zeile 1833 sieht wie folgt aus:

```
            try {
                if (data === 1000) {
                    // do not restart because of shut down of connection from the adapter
                    this.log.debug(`[wss.on - close]: ${reason}`);
                } else if (data === 1001) {
                    // every 2 hours
                    await this.autoRestart();
                } else if (data === 1012) {
                    // sometimes
                    await this.getAccessToken();
                    await this.autoRestart();
                } else if (data === 1006) {
                    // every 1 day
                    await this.getAccessToken();
                    await this.autoRestart();
                } else {
                    throw new Error('Unknown WebSocket error. (ERR_#011)');
                }
            } catch (error) {
                this.log.debug(`[wss.close - error]: ${error}`);
            }
```
Ich habe noch nicht getestet, ob das "await this.getAccessToken();" wirklich notwendig ist oder nicht, das kann ich erst sagen, wenn der Fehler das nächste Mal auftritt.

**Comment by reutli** [comment]
Same Problem here. The Code above should be included via PullRequest. @ice987987 can this be done shorthand?
