### ISSUE TITLE
nextStartTimestamp deleted when wss.on message received

### ISSUE THREAD

**Issue by Galileo53** [ice987987/ioBroker.husqvarna-automower#197]
### The problem

When starting the husqvarna-automower instance, the object "husqvarna-automower.0.xxxx....xxxx.planner.nextStartTimestamp is filled correctly with some timestamp.
The moment a wss.on message is received, the nextStartTimestamp object is set to NULL, even if this message contains a nextStartTimestamp entry with the same value as before.
After restarting the instance, the value is present again.

### Version of "husqvarna-automower"-adapter

0.5.0-beta.9

### Husqvarna Automower Type

430X NERA

### Version of Node.js

v20.17.0

### Version of ioBroker js-controller

6.0.11

### Version of "admin"-adapter

7.1.5

### Operating system incl. version running ioBroker

Windows 11 23H2

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode and check that there are no personal information)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

<html><body>

  | [wss.on  - message]:  {"id":"xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx","type":"status-event","attributes":{"battery":{"batteryPercent":99},"mower":{"mode":"MAIN_AREA","activity":"PARKED_IN_CS","state":"RESTRICTED","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":1727805600000,"override":{"action":"FORCE_PARK"},"restrictedReason":"PARK_OVERRIDE"},"metadata":{"connected":true,"statusTimestamp":1727775582027}}}
-- | --

</body>
</html>

**Comment by ice987987** [comment]
please try iobroker.husqvarna-automower >= v0.6.0-beta.8 on your testsystem

**Comment by Galileo53** [comment]
I have tried to install v0.6.0-beta.8 (or beta.x) for hours but did not succeed.
For example, if I go to "Install from URL / User defined" and type "https://github.com/ice987987/ioBroker.husqvarna-automower#v0.6.0-beta.8" I will always end up with version v0.5.0-beta.9 anyway.
If I try to install from the commandline, I get a lot of errors and the instance will then not start.
Can you please give me a hint how to install v0.6.0-beta.8 on my (Windows) system

**Comment by ice987987** [comment]
Uninstall the existing version, and install https://github.com/ice987987/ioBroker.husqvarna-automower/tree/v0.6.0-beta.x directly from github on your **non productive** installation.

**Comment by Galileo53** [comment]
Thank you for your support. I tried this before but for some reason it does not work. It end ends up with this error message:

`$ iobroker url https://github.com/ice987987/ioBroker.husqvarna-automower/tree/v0.6.0-beta.x --host XXXX --debug
install ice987987/ioBroker.husqvarna-automower#v0.6.0-beta.x
NPM version: 10.8.2
Installing ice987987/ioBroker.husqvarna-automower#v0.6.0-beta.x... (System call)
npm error code 128
npm error A complete log of this run can be found in: C:\Windows\system32\config\systemprofile\AppData\Local\npm-cache\_logs\2024-10-02T07_35_59_823Z-debug-0.log
host.XXXX Cannot install ice987987/ioBroker.husqvarna-automower#v0.6.0-beta.x: 128
ERROR: Process exited with code 25`

Note that https://github.com/ice987987/ioBroker.husqvarna-automower (without version specified) works perfectly.

Anyway, I have now re-installed the v0.5.0-beta.9 and simply copied over the main.js file from v0.6.0-beta.8.
This has fixed the problem. So you may close this issue. Thanks again.
