### ISSUE TITLE
Using your code in node without ioBroker

### ISSUE THREAD

**Issue by sgcl** [ice987987/ioBroker.husqvarna-automower#24]
Mathias,
Some years ago I started to use Node with the code from https://github.com/rannmann/node-husqvarna-automower but now that Husqvarna have published an official API I would like to set up something similar but using WebSocket to gather changes instead of reading the mower status every 3 minutes.  You have produced almost what I want but I don't want to install ioBroker. I just want to run a job on my Mac to gather the data and save it so it can be interpreted by a web page an example of which I attach. Do you have the code without reference to ioBroker which I may use please?
Kind regards,
Graham Lawrence    
Graham@GandJLawrence.co.uk
  
<img width="688" alt="image" src="https://user-images.githubusercontent.com/1127614/168994649-36e31836-587e-422d-95d5-7384c616f584.png">

**Comment by ice987987** [comment]
Hi Graham,
Thank you for your interest in this adapter. I took the initial code directly from husqvarna. Take a look at https://developer.husqvarnagroup.cloud/apis/Automower+Connect+API#/websocket, perhaps you can take some Ideas from there.

**Comment by sgcl** [comment]
Thank you for your help.
