### ISSUE TITLE
unhandled promise rejection "Automower Connect API" not reachable. (ERR_#005)

### ISSUE THREAD

**Issue by IllegalDuke** [ice987987/ioBroker.husqvarna-automower#65]
### The problem

Hello,

this evening the husqvarna-automower Adapter threw an error:

`<html>
<body>

husqvarna-automower.0 | 2022-10-19 19:41:31.421 | info | Connection to "Husqvarna WebSocket" established. Ready to get data...
-- | -- | -- | --
javascript.0 | 2022-10-19 19:41:31.160 | info | script.js.Skript_1: u0zuc3e35595
husqvarna-automower.0 | 2022-10-19 19:41:31.108 | info | Mowerdata initially saved.
husqvarna-automower.0 | 2022-10-19 19:41:30.746 | info | "Husqvarna Authentication API Access token" received.
husqvarna-automower.0 | 2022-10-19 19:41:30.452 | info | starting adapter "husqvarna-automower"...
husqvarna-automower.0 | 2022-10-19 19:41:30.410 | info | starting. Version 0.3.1-beta.1 (non-npm: ice987987/ioBroker.husqvarna-automower#development) in /opt/iobroker/node_modules/iobroker.husqvarna-automower, node: v16.16.0, js-controller: 4.0.23
host.ioBroker | 2022-10-19 19:41:29.295 | info | instance system.adapter.husqvarna-automower.0 started with pid 54658
host.ioBroker | 2022-10-19 19:40:59.219 | info | Restart adapter system.adapter.husqvarna-automower.0 because enabled
host.ioBroker | 2022-10-19 19:40:59.217 | error | instance system.adapter.husqvarna-automower.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
husqvarna-automower.0 | 2022-10-19 19:40:58.653 | info | cleaned everything up... (#1)
husqvarna-automower.0 | 2022-10-19 19:40:58.653 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
husqvarna-automower.0 | 2022-10-19 19:40:58.652 | info | terminating
husqvarna-automower.0 | 2022-10-19 19:40:58.471 | error | "Automower Connect API" not reachable. (ERR_#005)
husqvarna-automower.0 | 2022-10-19 19:40:58.471 | error | Error: "Automower Connect API" not reachable. (ERR_#005) at /opt/iobroker/node_modules/iobroker.husqvarna-automower/main.js:170:11 at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async HusqvarnaAutomower.getMowerData (/opt/iobroker/node_modules/iobroker.husqvarna-automower/main.js:142:3) at async Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.husqvarna-automower/main.js:97:5)
husqvarna-automower.0 | 2022-10-19 19:40:58.470 | error | unhandled promise rejection: "Automower Connect API" not reachable. (ERR_#005)
husqvarna-automower.0 | 2022-10-19 19:40:58.464 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

Seems like there is an unhandeled exception.

Please let me know, if you need more information.

BR
Daniel

### Version of Node.js

v16.16.0

### Version of ioBroker js-controller

 4.0.23

### Version of "husqvarna-automower"-adapter

v0.3.1-beta.1

### Version of "admin"-adapter

 v6.2.22

### Operating system incl. version running ioBroker

TrueNAS (FreeBSD-Jail) 12.2-RELEASE-p15

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode and check that there are no personal information)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by ice987987** [comment]
could you please check 0.3.1-beta.4:

https://github.com/ice987987/ioBroker.husqvarna-automower/tree/development

**Comment by IllegalDuke** [comment]
I have installed the beta.4 version right now and will give you feedback.

BR
Daniel

**Comment by IllegalDuke** [comment]
Hello,

the error still occurs:

<html>
<body>


husqvarna-automower.0 | 2022-10-23 12:28:24.471 | info | Connection to "Husqvarna WebSocket" established. Ready to get data...
-- | -- | -- | --
husqvarna-automower.0 | 2022-10-23 12:28:24.152 | info | Mowerdata initially saved.
husqvarna-automower.0 | 2022-10-23 12:28:23.842 | info | "Husqvarna Authentication API Access token" received.
husqvarna-automower.0 | 2022-10-23 12:28:23.567 | info | starting adapter "husqvarna-automower"...
husqvarna-automower.0 | 2022-10-23 12:28:23.546 | info | starting. Version 0.3.1-beta.4 (non-npm: ice987987/ioBroker.husqvarna-automower#development) in /opt/iobroker/node_modules/iobroker.husqvarna-automower, node: v16.16.0, js-controller: 4.0.23
host.ioBroker | 2022-10-23 12:28:22.163 | info | instance system.adapter.husqvarna-automower.0 started with pid 99096
host.ioBroker | 2022-10-23 12:27:52.095 | info | Restart adapter system.adapter.husqvarna-automower.0 because enabled
host.ioBroker | 2022-10-23 12:27:52.089 | error | instance system.adapter.husqvarna-automower.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
husqvarna-automower.0 | 2022-10-23 12:27:51.528 | info | cleaned everything up... (#1)
husqvarna-automower.0 | 2022-10-23 12:27:51.528 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
husqvarna-automower.0 | 2022-10-23 12:27:51.527 | info | terminating
husqvarna-automower.0 | 2022-10-23 12:27:51.362 | error | "Automower Connect API" not reachable. (ERR_#006)
husqvarna-automower.0 | 2022-10-23 12:27:51.362 | error | Error: "Automower Connect API" not reachable. (ERR_#006) at /opt/iobroker/node_modules/iobroker.husqvarna-automower/main.js:193:11 at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async HusqvarnaAutomower.getMowerData (/opt/iobroker/node_modules/iobroker.husqvarna-automower/main.js:156:3) at async Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.husqvarna-automower/main.js:102:5)
husqvarna-automower.0 | 2022-10-23 12:27:51.361 | error | unhandled promise rejection: "Automower Connect API" not reachable. (ERR_#006)
husqvarna-automower.0 | 2022-10-23 12:27:51.354 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>

BR
Daniel

**Comment by ice987987** [comment]
does this error occur while the adapter is running or after a manual restart?

**Comment by IllegalDuke** [comment]
It is happening during normal operation.
I have not restarted or manually started the Adapter since a few days…

But I remember a weird behaviour after a manual restart to switch the Adapter from Debug to Info and I restarted it twice within a short time period, because I accidently switched to „All“ and set it back to „Info“. This happened a few days ago. I will search for the Log File… It can be, that this failure occured beginning from that moment.

**Comment by IllegalDuke** [comment]
Hello,

I checked my old LOG-Files and it happened on 16.10.2022.

At 2022-10-16 19:39:42.941 I stopped the Automower Adapter to switch from Log-level "Debug" to "Info", but I accidently switched it to "Silly":
`2022-10-16 19:39:42.941 - info: host.ioBroker stopInstance system.adapter.husqvarna-automower.0 (force=false, process=true)`

At 2022-10-16 19:39:46.051 the Adapter startet again with the wrong Log-Level "Silly":
`2022-10-16 19:39:46.051 - info: host.ioBroker instance system.adapter.husqvarna-automower.0 started with pid 94037`

Then I switched the Log-Level to "Info" and the Adapter restartet again at 2022-10-16 19:39:47.756:
`2022-10-16 19:39:47.756 - info: host.ioBroker stopInstance system.adapter.husqvarna-automower.0 (force=false, process=true)`

Since that time I have seen the "Unhandled promise rejection".

I think something went wrong while I restarted the adapter after 1,5 seconds of running time due to my fault...
You can see details in my LOG:

[iobroker.2022-10-16.log](https://github.com/ice987987/ioBroker.husqvarna-automower/files/9846723/iobroker.2022-10-16.log)

Question is, how can I fix it, because I installed the new beta version in the meantime, that means the Adapter was restartet once since the first time the failure occured... Restart does not solve the problem.

**Comment by ice987987** [comment]
could you please try 0.3.1-beta.5:

https://github.com/ice987987/ioBroker.husqvarna-automower/tree/development

**Comment by IllegalDuke** [comment]
I installed it yesterday evening and have seen no errors until now. Will keep watching for errors the next days and give you Feedback.

**Comment by IllegalDuke** [comment]
Hello,

until now, the error did not occur again. Only thing I have seen is, that the Adapter showed following behaviour:
Verbunden mit Host - green
Lebenszeichen - green
Verbunden mit Gerät oder Dienst - NOT green

and the Adapter didn't work for about 12 hours until I recognized it and restarted the Adapter manually...
So I activated debug logging again, because the normal Info log did not show any message when and why that occured.
I will watch it closely a few days and give you feedback.

Until now it looks promising!

BR
Daniel

**Comment by ice987987** [comment]
Sounds good.

How long was the adapter running till „ Verbunden mit Gerät oder Dienst - NOT green“ happened? Which polling intervall did you set for statistics?

**Comment by IllegalDuke** [comment]
Hi,
polling interval is 720min.

<table>
  <tr>
    <th>Event</th>
    <th>Time</th>
  </tr>
  <tr>
    <td>I installed the adapter at</td>
    <td>2022-10-25 19:08:03.504</td>
  </tr>
  <tr>
    <td>The last logged data from the adapter was at</td>
    <td>2022-10-26 20:33:33</td>
  </tr>
  <tr>
    <td>I restarted the adapter at</td>
    <td>2022-10-27 17:30:04.145</td>
  </tr>
</table>

So it ran about 1 day before the adapter stopped working.
Now I am running in debug mode and have not seen any issues...

BR
Daniel

**Comment by IllegalDuke** [comment]
Hello,

update from my side: 
The error `"Automower Connect API" not reachable. (ERR_#006)` is still there, but does not lead to an `unhandled promise rejection: "Automower Connect API" not reachable. (ERR_#006)`.

It happens once a day, sometimes with the  `"Automower Connect API" not reachable. (ERR_#006)` error and sometimes without.

I added two log-files. One from 2022-11-01 10:13:33 with the (ERR_#006) and the second from 2022-11-02 10:12:08 without the error. -> Remark, the error is not really logged as a error, so I think it's more just for information.

The adapter keeps working after that "error", so I think everything is OK.

Thank you and BR
Daniel


[iobroker.2022-11-01_ERR006.log](https://github.com/ice987987/ioBroker.husqvarna-automower/files/9923584/iobroker.2022-11-01_ERR006.log)
[iobroker.2022-11-02.log](https://github.com/ice987987/ioBroker.husqvarna-automower/files/9923586/iobroker.2022-11-02.log)

**Comment by ice987987** [comment]
Hi Daniel,
thank you for your tests and investgation!
According to my understanding ERR_#006 comes if the request for updating the statistics is done but the key is no longer valid. Right after this error, a new key will be requested through the websocket-connection and everything works again. So ERR_#006 is not a classic error, more an information.
