### ISSUE TITLE
Automower Connect API not reachable

### ISSUE THREAD

**Issue by MatthiasUlrich1** [ice987987/ioBroker.husqvarna-automower#7]
Die Verbindung ist auf grün, jedoch werden keine Objekte angelegt.

Im Log steht <html><body>

  | Error: "Automower Connect API" not reachable. (ERR_#003)
-- | --

**Comment by intruder7777** [comment]
bei mir baut er die Verbindung auf und legt auch die Objekte an jedoch bricht die Verbindung nach einer Zeit ab und der Adapter geht auf rot. ein Neustart des Adapter reicht nicht. ich muss erst einmal in die Config und wieder raus. Danach lässt sich der Adapter wieder neustraten bis er irgendwann wieder auf rot geht

**Comment by intruder7777** [comment]
Ergänzung..... aktuell gehts auch nicht mehr

der Fehler kommt

<html>
<body>


error data: {"error":"invalid_request","error_description":"Simultaneous logins detected for client[id=cb526++++++++++54d], user[id=fdb494************36, email=*********}]","error_code":"simultaneous.logins"}
--



</body>
</html>

**Comment by MatthiasUlrich1** [comment]
Fehler gefunden: Die API muss nach dem anlegen der Application noch connected werden sonst läufts nicht.

**Comment by MK-2001** [comment]
> Fehler gefunden: Die API muss nach dem anlegen der Application noch connected werden sonst läufts nicht.

Hallo, 
Ich habe es gefunden. Das API Connect passiert im Husqvarna Portal:
https://developer.husqvarnagroup.cloud/applications/ 

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/36983163/228861300-86ad2c85-bd7c-4735-8044-add9eca5cc33.png">
