### ISSUE TITLE
Datenpunkt husqvarna-automower.0.XXXXXXX.planner.nextStartTimestamp

### ISSUE THREAD

**Issue by andre-bu** [ice987987/ioBroker.husqvarna-automower#9]
@ice987987 erst einmal vielen Dank und großes Lob für deine arbeit an diesem Adapter. 

Ich hab ein Problem mit dem Datenpunk "husqvarna-automower.0.XXXXXXX.planner.nextStartTimestamp"
Die Startzeit stimmt nicht mit der tatsächlichen Startzeit überein. Im Datenpunkt wird die Zeit 2h zu spät angezeigt. Im Mower und in der App stimmt sowohl die Startzeit als auch die Uhrzeit.
Hab den Adapter auf 2 unabhängigen IOBrokern. Auf beiden ist dieses Problemchen.

**Comment by ice987987** [comment]
Könntest du ggf. die Version v0.0.4 ausprobieren und prüfen?

**Comment by andre-bu** [comment]
@ice987987 

> Könntest du ggf. die Version v0.0.4 ausprobieren und prüfen?

mache ich sofort und gebe Rückmeldung.

**Comment by andre-bu** [comment]
@ice987987 
bei v0.0.4 stimmt die Startzeit. Vielen Dank. Dann schließe ich hier auch gleich.
