### ISSUE TITLE
Error on reading API for latitude

### ISSUE THREAD

**Issue by MK-2001** [ice987987/ioBroker.husqvarna-automower#97]
### The problem

When I start the instance and it is trying to connect to husqvarna, the adapter return an error:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/36983163/228799763-e7e56f7e-98a9-43c8-851f-4f73e3c947ec.png">

### Version of "husqvarna-automower"-adapter

installed from git

### Husqvarna Automower Type

405x

### Version of Node.js

14.20

### Version of ioBroker js-controller

4.0.24

### Version of "admin"-adapter

6.4.2

### Operating system incl. version running ioBroker

Linux Docker

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode and check that there are no personal information)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

Attached Screenshot above.

**Comment by ice987987** [comment]
- whitch version of ioBroker.husqvarna-automower is shown in the adapters-tab?
- could you set log on debug and show the log? be careful to remove all secrets and so on before posting

PS: node.js v14.x is quite old... please consider to update node.js

**Comment by MK-2001** [comment]
Version is v0.3.2-beta.1
I added a line of code to catch the issue. Please consider the PR.

**Comment by ice987987** [comment]
could it be that your installation is not correct and this is no longer an issue?

**Comment by MK-2001** [comment]
No, it is still the same. 
I have some areas where no gps is available on the device. Then comes the error... 

response.data: {"data":[{"type":"mower","id":"GUID","attributes":{"system":{"name":"BärAlgenCutter","model":"Husqvarna Automower® 405X","serialNumber":223000000000000000},"battery":{"batteryPercent":100},"mower":{"mode":"MAIN_AREA","activity":"NOT_APPLICABLE","state":"STOPPED","errorCode":0,"errorCodeTimestamp":0},"calendar":{"tasks":[{"start":780,"duration":420,"monday":true,"tuesday":true,"wednesday":true,"thursday":true,"friday":false,"saturday":false,"sunday":false}]},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1680184639659},**"positions":[]**,"settings":{"cuttingHeight":9,"headlight":{"mode":"ALWAYS_ON"}},"statistics":{"cuttingBladeUsageTime":0,"numberOfChargingCycles":0,"numberOfCollisions":0,"totalChargingTime":0,"totalCuttingTime":0,"totalRunningTime":0,"totalSearchingTime":0}}}]}
