### ISSUE TITLE
Add last state to the status within actions

### ISSUE THREAD

**Issue by MK-2001** [ice987987/ioBroker.husqvarna-automower#99]
### Feature or idea description

My expectation of ioBroker Adapters is, that if a state is acknowledged, then the state is the state which have been accepted by the adapter. When someone changes a "ACTION", then the state will be un-acknowledged. Within ioBroker it is possible to get the last acknowledged state as well. 

This adapter works different.

Detailed example:
`ACTIONS.HEADLIGHT` is per default "null". 

The state will be loaded into 
`settings.headlight`

May be I need some more explanation about the idea behind the separation of ACTIONS and the current status.

possible Solution:
The state could be copied with `ack:ture` to the ACTIONS for these statues. 

### Version of "husqvarna-automower"-adapter

v0.3.2-beta.1

### Additional information & file uploads

If you agree I will create a PR.

**Comment by ice987987** [comment]
I agree that `.settings.cuttingHeight` and `.settings.headlight` are available also in `ACTIONS.` So we can possibly merge them together.

**Comment by ice987987** [comment]
could you please check v0.3.3-beta.2 (https://github.com/ice987987/ioBroker.husqvarna-automower/tree/development) if this version meets your expectation?

**Comment by ice987987** [comment]
implemented with v0.4.0
